services:
  - type: web
    name: gympt
    env: python
    buildCommand: apt-get update && apt-get install -y libgl1 libglib2.0-0 && pip install -r requirements.txt
    startCommand: gunicorn app:app
